# Generated by Django 5.2 on 2025-04-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddproject', '0002_classe_idioma_raca_personagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='idioma',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='raca',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
